# Travis-CI Settings
language: python
python:
  - "2.7"

# Install dependencies.
before_install:
  - pip install coverage
  - pip install nose2
  - pip install python-coveralls

# Command to run tests.
script:
  - coverage run test.py

# Afterwards, run this.
after_script:
  - coveralls

