getting_started = '\n'.join([
    "GETTING STARTED",
    "Kelpy expressions are written inside curly braces. For example, to add the",
    "numbers 3 and 4, do:",
    "    {+ 3 4}",
    "We call the '+' the 'function name', and the 3 and 4 are 'arguments'.",
    "Kelpy uses the Polish prefix notation, meaning that the function comes before",
    "all of its arguments. This can be confusing at first, but you get used to it!",
    "",
    "Kelpy supports most math operations, and it even supports logical comparisons!",
    "    {== 3 3}",
    "    {!= 3 3}",
    "",
    "You can nest expressions inside of each other in most cases. Maybe you want",
    "to do some more advanced math:",
    "    {+ {/ 9 3} 2}",
    "",
    "In many cases, Kelpy can take as many arguments as you can give it!",
    "    {* 1 2 3 4 5 6 7}",
])
